site_name: HCL Digital Experience

theme:
  name: material
  logo: assets/dx_logo.png
  language: en
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - navigation.instant
    # - navigation.expand
    - search.highlight
    - search.share
    - search.suggest
    # - content.code.annotate
  extra_css:
    - stylesheets/dx_style.css
    - sofy.css
  # extra_javascript:
  #   - javascripts/sofy.js
  custom_dir: theme_overrides/
  icon:
    repo: fontawesome/brands/github
repo_url: https://pages.git.cwp.pnp-hcl.com/CWPdoc/dx-mkdocs/docs/
repo_name: CWPdoc/dx-mkdocs/docs/
plugins:
  - awesome-pages
  - search
# markdown_extensions:
#  - pymdownx.highlight:
